# This is a basic workflow to help you get started with Actions

name: CI-LINUX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: []
  pull_request:
    branches: []

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"
      - name: run make
        run: |

          npm install
          npm run dist

          mkdir -p /tmp/builds
          cd /home/runner/work/quest-sidenoder/quest-sidenoder/out/make/deb/x64/
          mkdir -p /tmp/builds/linux/deb/
          tar -cvf /tmp/builds/linux/deb/sidenoder-linux-x64-deb.tar *.deb
          cd /home/runner/work/quest-sidenoder/quest-sidenoder/out/make/rpm/x64/
          mkdir -p /tmp/builds/linux/rpm/
          tar -cvf /tmp/builds/linux/rpm/sidenoder-linux-x64-rpm.tar *.rpm
          cd /home/runner/work/quest-sidenoder/quest-sidenoder/out/make/zip/linux/x64/
          mkdir -p /tmp/builds/linux/zip/
          sudo mv *.zip /tmp/builds/linux/zip/

          cd /home/runner/work/quest-sidenoder/quest-sidenoder
          sudo rm -rf /home/runner/work/quest-sidenoder/quest-sidenoder/out

          sudo npm run-script dist

          mkdir -p /tmp/builds/AppImage/x64
          mkdir -p /tmp/builds/snap/x64

          cd /home/runner/work/quest-sidenoder/quest-sidenoder/dist/
          sudo mv sidenoder*.AppImage /tmp/builds/AppImage/x64/
          sudo mv sidenoder*.snap /tmp/builds/snap/x64/

      - name: Upload linux Build deb Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sidenoder-linux-x64-deb
          path: /tmp/builds/linux/deb/
      - name: Upload linux Build rpm Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sidenoder-linux-x64-rpm
          path: /tmp/builds/linux/rpm/
      - name: Upload linux Build zip Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sidenoder-linux-x64-zip
          path: /tmp/builds/linux/zip/

      - name: Upload linux Build appimage Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sidenoder-linux-x64-AppImage
          path: /tmp/builds/AppImage/x64/*.AppImage
      - name: Upload linux Build snap Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sidenoder-linux-x64-snap
          path: /tmp/builds/snap/x64/*.snap
